title = "device_config"

[color_camera_config]
color_camera = "/dev/video0"

debug_model = false
loop_count = 10
radius_ratio = 0.8  # ROI圆直径 占用整个相机试图的比例
detect_area_access_rate = 0.8  # 面积占比低于这个值直接返回unknow

colors = ["red","blue","green","white","black"]
# H_min H_max S_min S_max  V_min V_max
hsv_red  = [0,50,160,255,110,255]
hsv_blue  = [100, 137,124,255,56,255]
hsv_green = [50, 100,91,255,85,255]
hsv_black = [0, 179, 0, 255,0,76]
hsv_white = [0, 170, 0, 55,120,255]


[qr_camera_config]
qr_camera  = "/dev/video4"
debug_model = false


[cross_camera_config]
cross_camera = "/dev/video2"

[gpio_config]
serial = "dev/serial0"

baud = 115200   # or 9600
data_bit = 8
stop_bit = 1 
parity_bit = false #功能中尚未实现校验功能，也就是这个参数没用

[light_config]
color_light_pin = 17
qr_light_pin = 22
gpio_light_pin = 27
